# Configuration for Screenshot URLBox Module

# CSS selectors for header elements (prioritized order)
header_selectors:
  - "header"
  - "#header"
  - ".header"
  - "#main-header"
  - ".main-header"
  - "[role='banner']"
  - "nav"

# CSS selectors for footer elements (prioritized order)
footer_selectors:
  - "footer"
  - "#footer"
  - ".footer"
  - "#main-footer"
  - ".main-footer"
  - "[role='contentinfo']"

# CSS selectors for modal close buttons
modal_close_selectors:
  - "[aria-label*='close' i]"
  - "[aria-label*='dismiss' i]"
  - "[class*='close' i]"
  - "#modal-close"

# Default URLBox API options
screenshot_options:
  width: 1280
  delay: 5000  # Wait 5 seconds for page to fully render
  wait_until: loaded  # Wait for page load event
  timeout: 60000  # 60 second timeout for URLBox requests
